<?php
/** @var \BlueMedia\BluePayment\Block\Processing\Back $block */
?>

<?php if ($block->hasError()): ?>
    Wystąpił problem z Twoim zapytaniem.
<?php else: ?>

    <div class="back"
        data-mage-init='{
            "BlueMedia_BluePayment/js/customer/back":{
                "Status": "<?php echo $block->getOrderStatus() ?>",
                "OrderID": "<?php echo $block->getOrderId() ?>",
                "ServiceID": "<?php echo $block->getServiceId() ?>",
                "Hash": "<?php echo $block->getHash() ?>"
            }
        }'>
        <?php if ($block->getOrderStatus() == 'SUCCESS'): ?>
            <h2>Zamówienie przyjęte - <strong>Opłacone</strong></h2>

            <p>
                <strong>
                    Płatność za Twoje zamówienie przebiegła pomyślnie! Twoje zamówienie zostało przyjęte i przekazane do
                    realizacji.</strong>
            </p>

        <?php elseif ($block->getOrderStatus() == 'PENDING'): ?>
            <h2>Zamówienie przyjęte - <strong>Nieopłacone</strong></h2>

            <p>
                <strong>Twoje zamówienie zostało przyjęte i oczekuje na płatność.</strong>
            </p>

            <p>
                Strona automatycznie się przeładuje, jak tylko otrzymamy potwierdzenie Twojej płatności.
            </p>
        <?php elseif ($block->getOrderStatus() == 'FAILURE'): ?>
            <h2>Zamówienie przyjęte - <strong>Błąd płatności</strong></h2>

            <p>
                <strong>Twoje zamówienie zostało przyjęte, natomiast płatność nie powiodła się.</strong>
            </p>
        <?php endif; ?>

        <p>
            Numer zamówienia: <strong><?php echo $block->getOrderId(); ?></strong>
        </p>

    </div>
<?php endif; ?>
