<?php
/**
 * @var \BlueMedia\BluePayment\Block\ShortcutButton $block
 * @var \Magento\Framework\Escaper $escaper
 */

if ($block->isActive() && $block->getMerchantId()):
    $isInCatalogProduct = $block->isInCatalogProduct() ? true : false;
    $randStr = $block->getRandomId();

    $config = [
        'autopayShortcut' => [
            'isInCatalogProduct' => $block->isInCatalogProduct(),
            'selector' => $randStr,
            'merchantId' => $block->getMerchantId(),
            'language' => $block->getLanguage(),
            'minimumOrderConfiguration' => [
                'active' => $block->isMinimumOrderActive(),
                'amount' => $block->getMinimumOrderAmount(),
                'includingDiscount' => $block->isMinimumOrderIncludingDiscount(),
                'includingTax' => $block->isMinimumOrderIncludingTax(),
                'text' => $block->getMinimumOrderText(),
            ]
        ]
    ];
?>
    <div
        class="autopay-shortcut autopay-shortcut-<?= $randStr ?>"
        data-mage-init='<?= /* @noEscape */ \Magento\Framework\Serialize\JsonConverter::convert($config) ?>'>
        <div class="autopay-button"></div>
    </div>
<?php endif; ?>
