<?php
/** @var \BlueMedia\BluePayment\Block\ShortcutButton $block */

$isInCatalogProduct = false;
if ($block->getIsInCatalogProduct()) {
    $isInCatalogProduct = $block->getIsInCatalogProduct();
}
?>
<div class="autopay-shortcut" data-mage-init='{"autopayShortcut":{
    "isInCatalogProduct": "<?= /* @noEscape */ (bool)$block->getIsInCatalogProduct() ?>"
}}'>
    <div class="autopay-button"></div>
</div>
