<?php
/**
 * @var \BlueMedia\BluePayment\Block\ConsumerFinance $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>

<div class="bluemedia consumer-finance horizontal position-<?= $block->getPosition() ?>">
    <div class="cf-item later">
        <img src="<?= $this->getViewFileUrl('BlueMedia_BluePayment::images/cf/item1.svg'); ?>" alt="ZAPŁAĆ PÓŹNIEJ">

        <span class="label">ZAPŁAĆ PÓŹNIEJ</span>
        <span class="text">Kup teraz i zapłać w ciągu 30 dni</span>
    </div>

    <div class="cf-item installments">
        <img src="<?= $this->getViewFileUrl('BlueMedia_BluePayment::images/cf/item2.svg'); ?>" alt="RATY">

        <span class="label">RATY</span>
        <span class="text">Nawet 48 rat</span>
    </div>

    <div class="cf-item adj-installments">
        <img src="<?= $this->getViewFileUrl('BlueMedia_BluePayment::images/cf/item3.svg'); ?>" alt="DOPASOWANE RATY">

        <span class="label">DOPASOWANE RATY</span>
        <span class="text">Kup na dopasowane raty</span>
    </div>
</div>
