<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \BlueMedia\BluePayment\Block\Info $block
 */
$title = $block->escapeHtml($block->getMethod()->getTitle());

$gatewayId = $block->getInfo()->getAdditionalInformation('gateway_id');

?>
    <dl class="payment-method">
        <dt class="title"><?= /* @noEscape */ $title ?> - <?= $block->getGatewayNameFromQuote() ?></dt>
    </dl>
<?= $block->getChildHtml() ?>
