<?php
/**
 * @var \BlueMedia\BluePayment\Block\Info $block
 * @var \Magento\Framework\Escaper $escaper
 */
$title = $escaper->escapeHtml($block->getMethod()->getTitle());

$gatewayId = $block->getInfo()->getAdditionalInformation('gateway_id');

?>
    <dl class="payment-method">
        <dt class="title"><?= /* @noEscape */ $title ?> - <?= $block->getGatewayNameFromQuote() ?></dt>
    </dl>
<?= $block->getChildHtml() ?>
