<?php
/** @var \BlueMedia\BluePayment\Block\Analytics\Ga $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$accountId = $block->getAccountId();
$accountIdGa4 = $block->getAccountIdGa4();
?>

<?php if ($accountId): ?>
    <!-- BEGIN GOOGLE ANALYTICS CODE -->
    <script type="text/x-magento-init">
    {
        "*": {
            "BlueMedia_BluePayment/js/analytics/google-analytics": {
                "pageTrackingData": <?= /* @noEscape */ json_encode([
                    'isAnonymizedIpActive' => $block->isAnonymizedIpActive(),
                    'anonymizeIp' => $accountId,
                ]) ?>
            }
        }
    }
    </script>
    <!-- END GOOGLE ANALYTICS CODE -->
<?php endif; ?>

<?php if ($accountIdGa4): ?>
    <script async
            src="https://www.googletagmanager.com/gtag/js?id=<?= $block->escapeHtmlAttr($accountIdGa4) ?>">
    </script>

    <?php
    $content = <<<JS
window.dataLayer = window.dataLayer || [];
function gtag () {
    dataLayer.push(arguments);
}

gtag('js', new Date());
gtag('set', {'currency': '{$block->getCurrency()}'});
gtag(
    'config',
    '{$block->escapeHtmlAttr($accountIdGa4)}'
);
JS;

    if ($block->isAnonymizedIpActive()) {
        $content .= "\n gtag('set', {'anonymize_ip': true});";
    }
    ?>

    <?php if (isset($secureRenderer)): ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $content, false); ?>
    <?php else: ?>
        <?= /* @noEscape */ "<script>" . $content . "</script>" ?>
    <?php endif; ?>

    <script type="text/x-magento-init">
    {
        "*": {
            "BlueMedia_BluePayment/js/analytics/ga4-client-id": {
                "client_id": "<?= $block->escapeHtmlAttr($accountIdGa4) ?>"
            },
            "BlueMedia_BluePayment/js/analytics/cart": {}
        }
    }
    </script>
<?php endif; ?>
