<?php
/**
 * @var \BlueMedia\BluePayment\Block\ConsumerFinance $block
 */
?>
<?php if ($block->isEnabled()): ?>
    <div class="bluemedia consumer-finance horizontal position-<?= $block->getPosition() ?>">
        <?php if ($block->isInstallmentsAvailable()): ?>
            <div class="cf-item installments">
                <span class="label"><?= __('INSTALLMENTS') ?></span>
                <span class="text"><?= __('Up to 48 installments') ?></span>
            </div>
        <?php endif; ?>

        <?php if ($block->isHubAvailable()): ?>
            <div class="cf-item hub">
                <span class="label"><?= __('TAILORED INSTALLMENTS') ?></span>
                <span class="text"><?= __('Buy on tailored installments') ?></span>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
