<?php
/**
 * @var \BlueMedia\BluePayment\Block\ConsumerFinance $block
 */
?>
<?php if ($block->isEnabled()): ?>
    <div class="bluemedia consumer-finance vertical position-<?= /* @noEscape */ $block->getPosition() ?>">
        <?php if ($block->isInstallmentsAvailable()): ?>
            <div class="cf-item installments">
                <img src="<?= /* @noEscape */ $this->getViewFileUrl('BlueMedia_BluePayment::images/consumer-finance/item2.svg'); ?>" alt="RATY">

                <span class="label"><?= /* @noEscape */ __('INSTALLMENTS') ?></span>
                <span class="text"><?= /* @noEscape */ __('Up to 48 installments') ?></span>
            </div>
        <?php endif; ?>

        <?php if ($block->isHubAvailable()): ?>
            <div class="cf-item hub">
                <img src="<?= /* @noEscape */ $this->getViewFileUrl('BlueMedia_BluePayment::images/consumer-finance/item3.svg'); ?>" alt="DOPASOWANE RATY">

                <span class="label"><?= /* @noEscape */ __('TAILORED INSTALLMENTS') ?></span>
                <span class="text"><?= /* @noEscape */ __('Buy on tailored installments') ?></span>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
