<?php
/**
 * @var $block \BlueMedia\BluePayment\Block\Adminhtml\System\Config\Form\Field\ConsumerFinanceInfo
 */
?>

<div class="consumer-finance">
    <h2><?= /* @noEscape */ __('Why promote?'); ?></h2>
    <ul>
        <li>
            <img src="<?= /* @noEscape */ $this->getViewFileUrl('BlueMedia_BluePayment::images/consumer-finance/item1.svg'); ?>" alt="Większa sprzedaż">
            <?= /* @noEscape */ __('More sales'); ?>
        </li>
        <li>
            <img src="<?= /* @noEscape */ $this->getViewFileUrl('BlueMedia_BluePayment::images/consumer-finance/item2.svg'); ?>" alt="Mniej porzuconych koszyków">
            <?= /* @noEscape */ __('Fewer abandoned shopping carts'); ?>
        </li>
        <li>
            <img src="<?= /* @noEscape */ $this->getViewFileUrl('BlueMedia_BluePayment::images/consumer-finance/item3.svg'); ?>" alt="Więcej klientów">
            <?= /* @noEscape */ __('More customers'); ?>
        </li>
    </ul>

    <?= /* @noEscape */ __('Customers are more likely to decide to buy products, even at a higher price, if they can pay later or spread the repayment in installments.'); ?>
</div>
