<?php
/**
 * @var $block \BlueMedia\BluePayment\Block\Adminhtml\System\Config\Form\Field\Introduction
 */
?>

<div class="introduction">
    <div class="introduction--row">
        <div class="introduction--col">
            <div class="introduction--check"></div>
            <div class="introduction--content">
                <a href="https://platnosci.bm.pl/?pk_campaign=magento_panel&pk_source=magento_panel&pk_medium=cta"
                   target="_blank" class="introduction--link"><?= __('Fee only 1,19%.') ?></a>
            </div>
        </div>
        <div class="introduction--col">
            <div class="introduction--check"></div>
            <div class="introduction--content">
                <?= __('Prepare store regulations 10% off.') ?><br />
                <a href="https://developers.bluemedia.pl/legal-geek?mtm_campaign=magento_legalgeek&mtm_source=magento_backoffice&mtm_medium=cta"
                   target="_blank" class="introduction--link"><?= __('Learn more') ?></a>
            </div>
        </div>
    </div>

    <h2><?= __('How to get started?') ?></h2>

    <div class="introduction--row">
        <div class="introduction--col">
            <div class="introduction--num">1</div>
            <div class="introduction--content introduction--content__padding">
                <?= __('Create a free account on the site.') ?><br />
                <a href="https://platnosci.bm.pl/?pk_campaign=magento_panel&pk_source=magento_panel&pk_medium=cta"
                   class="introduction--link" target="_blank"><?= __('Register') ?></a>
            </div>
        </div>
        <div class="introduction--col">
            <div class="introduction--num">2</div>
            <div class="introduction--content introduction--content__padding">
                <?= __('Enter your company details and confirm them with a verification transfer.') ?>
            </div>
        </div>
        <div class="introduction--col">
            <div class="introduction--num">3</div>
            <div class="introduction--content introduction--content__padding">
                <?= __('Set up payments in your store.') ?>
            </div>
        </div>
    </div>

    <p class="introduction--learn-more">
        <a href="https://developers.bluemedia.pl/online/wdrozenie-krok-po-kroku?mtm_campaign=magento_developers_aktywacja_platnosci&mtm_source=magento_backend&mtm_medium=hyperlink"
           target="_blank" class="introduction--link"><?= __('Learn more') ?></a>
        <?= __('about implementing payments in your store.') ?>
    </p>
</div>
