<?php
/**
 * @var $block \BlueMedia\BluePayment\Block\Adminhtml\System\Config\Form\Field\TestMode
 */
?>

<tr id="row_payment_bluepayment_test_mode_info">
    <td colspan="3">
        <div class="messages">
            <div class="message message-info">
                <div data-ui-id="messages-message-info">
                    <?= /* @noEscape */ __('Partner\'s website ID and Shared key are different for production and testing environment.') ?><br />
                    <?= /* @noEscape */ __('To get the data for the test environment,') ?> <a href="https://developers.autopay.pl/kontakt?mtm_campaign=magento_developers_formularz&mtm_source=magento_backoffice&mtm_medium=hiperlink" target="_blank"><?= /* @noEscape */ __('contact us') ?></a>.
                </div>
            </div>
        </div>
    </td>
</tr>
