<?php
/**
 * @var $block \BlueMedia\BluePayment\Block\Adminhtml\System\Config\Form\Field\WidgetDocumentation
 */
?>

<tr id="row_payment_bluepayment_widget_documentation_info">
    <td colspan="3">
        <div class="messages">
            <div class="message message-warning">
                <div data-ui-id="messages-message-warning">
                    <?= __('Each merchant who wants to enable Autopay Widget must complete required documentation with a business account manager.') ?><br />
                    <?= __('Only after this formal process should Widget Payment be enabled.') ?>
                </div>
            </div>
        </div>
    </td>
</tr>
