<?php
/** @var \BlueMedia\BluePayment\Block\Form $block */

// Unikatowy identyfikator
$code = $block->getMethodCode();

// Adres do pliku z logo firmy
$img = $block->getLogoSrc();
?>

<ul class="bluemediatest123 form-list"
    id="payment_form_<?= /* @noEscape */ $code ?>"
    style="display:none;"
>
    <?php if ($img): ?>
        <img src="<?= /* @noEscape */ $img ?>" alt="Blue Media Logo" /><br />
    <?php endif; ?>
    <li class="form-alt">
        <?=
        /* @noEscape */
        __('You will be redirected to the Blue Media secure service payment after submitting the order.')
        ?>
    </li>
</ul>

<script>
    //<![CDATA[
    var $gateways = jQuery('#p_method_bluepayment_gateway');
    jQuery(document).ready(function () {

        $interval = setInterval(function () {
            jQuery('#p_method_bluepayment_gateway').find('input:radio').each(function () {
                jQuery(this).removeAttr('disabled');
            });
        }, 50);
        setTimeout(function () {
            clearInterval($interval);
        }, 1000);

        var $bluepaymentInput = jQuery('#p_method_bluepayment');
        if ($bluepaymentInput.length) {
            setDefaultDisplayGateways($bluepaymentInput);

            jQuery('input:radio[name="payment[method]"]').change(function () {
                if (jQuery(this).val() === 'bluepayment') {
                    showGateways();
                } else {
                    hideGateways();
                }
            });
        }
    });

    function setDefaultDisplayGateways(input) {
        if ($gateways.length) {
            $gateways.find('input:radio').each(function () {
                jQuery(this).prop('disabled', false);
            });
            if (input.is(':checked')) {
                $gateways.show();
            } else {
                $gateways.hide();
            }
        }
    }

    function showGateways() {
        if ($gateways.length) {
            $gateways.find('input:radio').each(function () {
                jQuery(this).prop('disabled', false);
            });
            $gateways.show();
        }
    }
    function hideGateways() {
        if ($gateways.length) {
            $gateways.hide();
        }
    }
    //]]>
</script>
