<?php
/* @var \Magento\Framework\View\Element\Template $block */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="<?= /* @noEscape */ $block->getLang() ?>"
      lang="<?= /* @noEscape */ $block->getLang() ?>"
>
    <body>
        <?= /* @noEscape */ $block->getForm(); ?>
        <script type="text/javascript">document.getElementById("bluepayment_checkout").submit();</script>
    </body>
</html>